import type { Config } from 'tailwindcss';

const config: Config = {
    darkMode: ['class'],
    content: [
        './pages/**/*.{js,ts,jsx,tsx,mdx}',
        './components/**/*.{js,ts,jsx,tsx,mdx}',
        './app/**/*.{js,ts,jsx,tsx,mdx}',
        './lib/**/*.{js,ts,jsx,tsx}',
    ],
    theme: {
        extend: {
            colors: {
                // PropReady Brand Colors
                primary: {
                    DEFAULT: '#004D40', // Deep green
                    50: '#E0F2F1',
                    100: '#B2DFDB',
                    200: '#80CBC4',
                    300: '#4DB6AC',
                    400: '#26A69A',
                    500: '#009688',
                    600: '#00897B',
                    700: '#00796B',
                    800: '#00695C',
                    900: '#004D40',
                },
                gold: {
                    DEFAULT: '#DC2626',
                    50: '#FEF2F2',
                    100: '#FEE2E2',
                    200: '#FECACA',
                    300: '#FCA5A5',
                    400: '#F87171',
                    500: '#EF4444',
                    600: '#DC2626',
                    700: '#B91C1C',
                    800: '#991B1B',
                    900: '#7F1D1D',
                },
                charcoal: {
                    DEFAULT: '#2C2C2C',
                    50: '#F5F5F5',
                    100: '#E0E0E0',
                    200: '#BDBDBD',
                    300: '#9E9E9E',
                    400: '#757575',
                    500: '#616161',
                    600: '#424242',
                    700: '#2C2C2C',
                    800: '#212121',
                    900: '#121212',
                },
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                chart: {
                    '1': 'hsl(var(--chart-1))',
                    '2': 'hsl(var(--chart-2))',
                    '3': 'hsl(var(--chart-3))',
                    '4': 'hsl(var(--chart-4))',
                    '5': 'hsl(var(--chart-5))',
                },
            },
            spacing: {
                'foundation-1': 'var(--space-1)',
                'foundation-2': 'var(--space-2)',
                'foundation-3': 'var(--space-3)',
                'foundation-4': 'var(--space-4)',
                'foundation-5': 'var(--space-5)',
                'foundation-6': 'var(--space-6)',
                'foundation-7': 'var(--space-7)',
                'foundation-8': 'var(--space-8)',
                'foundation-10': 'var(--space-10)',
                'foundation-12': 'var(--space-12)',
                'foundation-16': 'var(--space-16)',
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
                'foundation-xs': 'var(--radius-xs)',
                'foundation-sm': 'var(--radius-sm)',
                'foundation-md': 'var(--radius-md)',
                'foundation-lg': 'var(--radius-lg)',
                'foundation-xl': 'var(--radius-xl)',
                'foundation-2xl': 'var(--radius-2xl)',
            },
            boxShadow: {
                'elevation-xs': 'var(--shadow-xs)',
                'elevation-sm': 'var(--shadow-sm)',
                'elevation-md': 'var(--shadow-md)',
                'elevation-lg': 'var(--shadow-lg)',
                'elevation-xl': 'var(--shadow-xl)',
                'elevation-hover': 'var(--shadow-hover)',
                'elevation-lift': 'var(--shadow-lift)',
                'elevation-gold': 'var(--shadow-gold)',
                'elevation-gold-hover': 'var(--shadow-gold-hover)',
                'elevation-focus': 'var(--shadow-focus)',
                'btn': 'var(--shadow-btn)',
                'btn-hover': 'var(--shadow-btn-hover)',
                'card': 'var(--shadow-card)',
                'card-hover': 'var(--shadow-card-hover)',
            },
            transitionDuration: {
                instant: 'var(--duration-instant)',
                150: 'var(--duration-fast)',
                200: 'var(--duration-base)',
                250: 'var(--duration-card)',
                300: 'var(--duration-moderate)',
                400: 'var(--duration-slow)',
            },
            transitionTimingFunction: {
                standard: 'var(--ease-standard)',
                'out-soft': 'var(--ease-out)',
                'in-out-soft': 'var(--ease-in-out)',
            },
            width: {
                'icon-xs': 'var(--icon-xs)',
                'icon-sm': 'var(--icon-sm)',
                'icon-md': 'var(--icon-md)',
                'icon-lg': 'var(--icon-lg)',
                'icon-xl': 'var(--icon-xl)',
                'icon-2xl': 'var(--icon-2xl)',
            },
            height: {
                'icon-xs': 'var(--icon-xs)',
                'icon-sm': 'var(--icon-sm)',
                'icon-md': 'var(--icon-md)',
                'icon-lg': 'var(--icon-lg)',
                'icon-xl': 'var(--icon-xl)',
                'icon-2xl': 'var(--icon-2xl)',
            },
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
};

export default config;
