import type {
    ConveyancerProfile,
    ProvinceSlug,
    Specialty,
} from '@/lib/conveyancer-connect/types';

function review(
    id: string,
    author: string,
    role: ConveyancerProfile['reviews'][0]['role'],
    rating: number,
    title: string,
    body: string,
    date: string,
    helpful: number,
    response?: string
): ConveyancerProfile['reviews'][0] {
    const base = Math.max(3.5, rating - 0.2);
    return {
        id,
        author,
        role,
        rating,
        axes: {
            communication: base + 0.1,
            professionalism: rating,
            transparency: base,
            value: base - 0.1,
            speed: base,
            knowledge: rating,
            overall: rating,
        },
        title,
        body,
        date,
        verified: true,
        helpful,
        response,
    };
}

const commonServices: Specialty[] = [
    'residential',
    'bond-registration',
    'bond-cancellation',
    'sectional-title',
    'family-transfers',
];

export const CONVEYANCERS: ConveyancerProfile[] = [
    {
        id: 'cc-01',
        slug: 'horizon-transfer-attorneys',
        firmName: 'Horizon Transfer Attorneys',
        attorneyName: 'Thandiwe Nkosi',
        title: 'Director & Conveyancer',
        verified: true,
        featured: true,
        logoInitials: 'HT',
        photoInitials: 'TN',
        accent: '#0F766E',
        rating: 4.9,
        reviewCount: 218,
        completedTransfers: 1840,
        yearsInPractice: 16,
        province: 'gauteng',
        city: 'Johannesburg',
        suburb: 'Sandton',
        languages: ['English', 'Zulu', 'Afrikaans'],
        avgResponseHours: 1.2,
        avgTransferDays: 62,
        priceBand: 3,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'investment-property', 'bond-registration', 'developments'],
        bio: 'Thandiwe leads a Sandton-based conveyancing practice known for transparent fee schedules, rapid FICA turnaround, and developer-ready sectional title transfers across Gauteng.',
        firmHistory: 'Founded in 2009 to modernise residential conveyancing for private buyers and boutique developers in northern Johannesburg.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer', 'Notary Public'],
        education: ['LLB — University of the Witwatersrand', 'Certificate in Property Law — LEAD'],
        memberships: ['Legal Practice Council', 'Black Lawyers Association'],
        awards: ['PropReady Verified Excellence 2025'],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Sandton HQ',
                address: '12 Rivonia Rd, Sandhurst',
                suburb: 'Sandton',
                city: 'Johannesburg',
                province: 'gauteng',
                coords: { lat: -26.1076, lng: 28.0567 },
            },
        ],
        services: [...commonServices, 'developments', 'investment-property', 'portfolio'],
        performance: {
            avgTransferDays: 62,
            avgResponseHours: 1.2,
            clientSatisfactionPct: 97,
            repeatClientPct: 41,
            transfersCompleted: 1840,
            successRatePct: 99.1,
            currentWorkload: 28,
            monthlyCases: 42,
            avgReview: 4.9,
            yearsActive: 16,
            responseRatePct: 98,
        },
        reviews: [
            review('r1', 'Lebo M.', 'buyer', 5, 'Seamless Sandton purchase', 'Clear updates every week and lodgement ahead of schedule.', '2026-05-12', 24, 'Thank you — delighted to assist.'),
            review('r2', 'Cate V.', 'investor', 4.8, 'Portfolio transfers handled well', 'Managed three sectional title units without drama.', '2026-03-02', 11),
        ],
        documents: [
            { label: 'Practice Certificate', type: 'PDF' },
            { label: 'LPC Membership', type: 'PDF' },
            { label: 'Office photo — reception', type: 'Image' },
        ],
        phone: '+27 11 555 0140',
        email: 'hello@horizontransfer.demo',
        website: 'https://example.com/horizon',
        lastActiveAt: '2026-07-30T09:00:00Z',
        coords: { lat: -26.1076, lng: 28.0567 },
    },
    {
        id: 'cc-02',
        slug: 'atlantic-title-partners',
        firmName: 'Atlantic Title Partners',
        attorneyName: 'Johan du Plessis',
        title: 'Senior Conveyancer',
        verified: true,
        featured: true,
        logoInitials: 'AT',
        photoInitials: 'JD',
        accent: '#1D4ED8',
        rating: 4.8,
        reviewCount: 162,
        completedTransfers: 1210,
        yearsInPractice: 14,
        province: 'western-cape',
        city: 'Cape Town',
        suburb: 'Cape Town City Bowl',
        languages: ['English', 'Afrikaans'],
        avgResponseHours: 2.0,
        avgTransferDays: 68,
        priceBand: 3,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'commercial', 'sectional-title', 'estate-transfers'],
        bio: 'Atlantic Title Partners specialises in City Bowl and Atlantic Seaboard transfers with bilingual support and strong bank guarantee coordination.',
        firmHistory: 'Cape Town practice established in 2012 with a focus on coastal residential and boutique commercial transfers.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — University of Stellenbosch'],
        memberships: ['Legal Practice Council', 'Cape Law Society (legacy)'],
        awards: ['Client Choice Conveyancing 2024'],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'City Bowl',
                address: '88 Bree Street',
                suburb: 'Cape Town City Bowl',
                city: 'Cape Town',
                province: 'western-cape',
                coords: { lat: -33.9249, lng: 18.4241 },
            },
        ],
        services: [...commonServices, 'commercial', 'estate-transfers', 'deceased-estates'],
        performance: {
            avgTransferDays: 68,
            avgResponseHours: 2,
            clientSatisfactionPct: 95,
            repeatClientPct: 36,
            transfersCompleted: 1210,
            successRatePct: 98.6,
            currentWorkload: 22,
            monthlyCases: 31,
            avgReview: 4.8,
            yearsActive: 14,
            responseRatePct: 96,
        },
        reviews: [
            review('r3', 'Amira S.', 'seller', 4.9, 'Clear fee estimate', 'Knew exactly what I would pay before instruction.', '2026-06-01', 18),
        ],
        documents: [
            { label: 'Practice Certificate', type: 'PDF' },
            { label: 'Team photo', type: 'Image' },
        ],
        phone: '+27 21 555 0192',
        email: 'matters@atlantictitle.demo',
        website: 'https://example.com/atlantic',
        lastActiveAt: '2026-07-29T14:20:00Z',
        coords: { lat: -33.9249, lng: 18.4241 },
    },
    {
        id: 'cc-03',
        slug: 'umhlanga-conveyancing-group',
        firmName: 'Umhlanga Conveyancing Group',
        attorneyName: 'Priya Naidoo',
        title: 'Managing Partner',
        verified: true,
        featured: true,
        logoInitials: 'UC',
        photoInitials: 'PN',
        accent: '#B45309',
        rating: 4.7,
        reviewCount: 141,
        completedTransfers: 980,
        yearsInPractice: 12,
        province: 'kwazulu-natal',
        city: 'Durban',
        suburb: 'Umhlanga',
        languages: ['English', 'Zulu', 'Hindi'],
        avgResponseHours: 1.8,
        avgTransferDays: 70,
        priceBand: 2,
        acceptingNewClients: true,
        openToday: false,
        onlineConsultation: true,
        availability: 'limited',
        specialisations: ['residential', 'developments', 'sectional-title', 'investment-property'],
        bio: 'Priya’s team is trusted by North Coast developers and private buyers for sectional schemes and holiday-home transfers.',
        firmHistory: 'Opened in Umhlanga in 2014 to serve KZN’s coastal growth corridor.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer', 'Notary Public'],
        education: ['LLB — UKZN'],
        memberships: ['Legal Practice Council'],
        awards: [],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Umhlanga Ridge',
                address: '4 Lagoon Drive',
                suburb: 'Umhlanga',
                city: 'Durban',
                province: 'kwazulu-natal',
                coords: { lat: -29.7285, lng: 31.0853 },
            },
        ],
        services: [...commonServices, 'developments', 'investment-property'],
        performance: {
            avgTransferDays: 70,
            avgResponseHours: 1.8,
            clientSatisfactionPct: 94,
            repeatClientPct: 33,
            transfersCompleted: 980,
            successRatePct: 98.2,
            currentWorkload: 34,
            monthlyCases: 27,
            avgReview: 4.7,
            yearsActive: 12,
            responseRatePct: 94,
        },
        reviews: [
            review('r4', 'Grant H.', 'developer', 4.7, 'Scheme registration expertise', 'Understood body corporate nuances immediately.', '2026-04-18', 9),
        ],
        documents: [{ label: 'Practice Certificate', type: 'PDF' }],
        phone: '+27 31 555 0118',
        email: 'desk@umhlangacg.demo',
        website: 'https://example.com/umhlanga',
        lastActiveAt: '2026-07-28T11:00:00Z',
        coords: { lat: -29.7285, lng: 31.0853 },
    },
    {
        id: 'cc-04',
        slug: 'pretoria-deedcraft',
        firmName: 'Pretoria DeedCraft',
        attorneyName: 'Mpho Molefe',
        title: 'Conveyancer',
        verified: true,
        featured: false,
        logoInitials: 'PD',
        photoInitials: 'MM',
        accent: '#7C3AED',
        rating: 4.6,
        reviewCount: 96,
        completedTransfers: 740,
        yearsInPractice: 9,
        province: 'gauteng',
        city: 'Pretoria',
        suburb: 'Brooklyn',
        languages: ['English', 'Northern Sotho', 'Afrikaans'],
        avgResponseHours: 2.5,
        avgTransferDays: 66,
        priceBand: 2,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'bond-cancellation', 'family-transfers', 'divorce-transfers'],
        bio: 'Brooklyn-based conveyancer focused on family transfers, divorce settlements, and efficient bond cancellations in Tshwane.',
        firmHistory: 'Independent practice launched in 2017 after years at a national firm.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — University of Pretoria'],
        memberships: ['Legal Practice Council'],
        awards: [],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Brooklyn',
                address: '220 Bronkhorst Street',
                suburb: 'Brooklyn',
                city: 'Pretoria',
                province: 'gauteng',
                coords: { lat: -25.771, lng: 28.234 },
            },
        ],
        services: [...commonServices, 'divorce-transfers', 'trust-transfers'],
        performance: {
            avgTransferDays: 66,
            avgResponseHours: 2.5,
            clientSatisfactionPct: 93,
            repeatClientPct: 29,
            transfersCompleted: 740,
            successRatePct: 98.0,
            currentWorkload: 18,
            monthlyCases: 22,
            avgReview: 4.6,
            yearsActive: 9,
            responseRatePct: 92,
        },
        reviews: [
            review('r5', 'Nadia K.', 'seller', 4.6, 'Patient with divorce transfer', 'Handled sensitive instructions with care.', '2026-02-14', 7),
        ],
        documents: [{ label: 'Practice Certificate', type: 'PDF' }],
        phone: '+27 12 555 0166',
        email: 'info@deedcraft.demo',
        website: 'https://example.com/deedcraft',
        lastActiveAt: '2026-07-30T07:40:00Z',
        coords: { lat: -25.771, lng: 28.234 },
    },
    {
        id: 'cc-05',
        slug: 'stellenbosch-title-lab',
        firmName: 'Stellenbosch Title Lab',
        attorneyName: 'Ané Botha',
        title: 'Partner',
        verified: true,
        featured: true,
        logoInitials: 'ST',
        photoInitials: 'AB',
        accent: '#BE123C',
        rating: 4.85,
        reviewCount: 128,
        completedTransfers: 860,
        yearsInPractice: 11,
        province: 'western-cape',
        city: 'Stellenbosch',
        suburb: 'Stellenbosch Central',
        languages: ['Afrikaans', 'English'],
        avgResponseHours: 1.5,
        avgTransferDays: 64,
        priceBand: 3,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: false,
        availability: 'available',
        specialisations: ['residential', 'estate-transfers', 'deceased-estates', 'trust-transfers'],
        bio: 'Wine-route specialists in estate and trust transfers with meticulous client education on timelines and costs.',
        firmHistory: 'Boutique Stellenbosch firm founded in 2015.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer', 'Notary Public'],
        education: ['LLB — Stellenbosch University'],
        memberships: ['Legal Practice Council'],
        awards: ['Winelands Professional Service Award'],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Dorpsig',
                address: '15 Church Street',
                suburb: 'Stellenbosch Central',
                city: 'Stellenbosch',
                province: 'western-cape',
                coords: { lat: -33.9321, lng: 18.8602 },
            },
        ],
        services: [...commonServices, 'estate-transfers', 'deceased-estates', 'trust-transfers'],
        performance: {
            avgTransferDays: 64,
            avgResponseHours: 1.5,
            clientSatisfactionPct: 96,
            repeatClientPct: 38,
            transfersCompleted: 860,
            successRatePct: 98.8,
            currentWorkload: 16,
            monthlyCases: 24,
            avgReview: 4.85,
            yearsActive: 11,
            responseRatePct: 97,
        },
        reviews: [
            review('r6', 'Pieter L.', 'buyer', 5, 'Estate transfer clarity', 'Explained every step of the deceased estate path.', '2026-01-22', 14),
        ],
        documents: [
            { label: 'Practice Certificate', type: 'PDF' },
            { label: 'Notary Certificate', type: 'PDF' },
        ],
        phone: '+27 21 555 0288',
        email: 'team@titlelab.demo',
        website: 'https://example.com/titlelab',
        lastActiveAt: '2026-07-30T10:15:00Z',
        coords: { lat: -33.9321, lng: 18.8602 },
    },
    {
        id: 'cc-06',
        slug: 'east-london-transfer-desk',
        firmName: 'East London Transfer Desk',
        attorneyName: 'Sipho Dlamini',
        title: 'Principal',
        verified: true,
        featured: false,
        logoInitials: 'EL',
        photoInitials: 'SD',
        accent: '#0369A1',
        rating: 4.5,
        reviewCount: 64,
        completedTransfers: 420,
        yearsInPractice: 8,
        province: 'eastern-cape',
        city: 'East London',
        suburb: 'Berea',
        languages: ['English', 'Xhosa'],
        avgResponseHours: 3.0,
        avgTransferDays: 74,
        priceBand: 1,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'bond-registration', 'family-transfers'],
        bio: 'Accessible Eastern Cape conveyancing with strong bilingual support and competitive fee bands.',
        firmHistory: 'Community-focused practice serving East London and surrounds since 2018.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — Nelson Mandela University'],
        memberships: ['Legal Practice Council'],
        awards: [],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Berea',
                address: '44 Pearce Street',
                suburb: 'Berea',
                city: 'East London',
                province: 'eastern-cape',
                coords: { lat: -33.0153, lng: 27.9116 },
            },
        ],
        services: [...commonServices],
        performance: {
            avgTransferDays: 74,
            avgResponseHours: 3,
            clientSatisfactionPct: 91,
            repeatClientPct: 27,
            transfersCompleted: 420,
            successRatePct: 97.5,
            currentWorkload: 12,
            monthlyCases: 14,
            avgReview: 4.5,
            yearsActive: 8,
            responseRatePct: 90,
        },
        reviews: [
            review('r7', 'Lindiwe P.', 'buyer', 4.5, 'Fair fees', 'Best value quote we received locally.', '2025-11-09', 5),
        ],
        documents: [{ label: 'Practice Certificate', type: 'PDF' }],
        phone: '+27 43 555 0101',
        email: 'office@eltransfer.demo',
        website: 'https://example.com/eltransfer',
        lastActiveAt: '2026-07-27T16:00:00Z',
        coords: { lat: -33.0153, lng: 27.9116 },
    },
    {
        id: 'cc-07',
        slug: 'midrand-metro-conveyancers',
        firmName: 'Midrand Metro Conveyancers',
        attorneyName: 'Fatima Essop',
        title: 'Director',
        verified: true,
        featured: false,
        logoInitials: 'MM',
        photoInitials: 'FE',
        accent: '#0F766E',
        rating: 4.55,
        reviewCount: 88,
        completedTransfers: 610,
        yearsInPractice: 10,
        province: 'gauteng',
        city: 'Midrand',
        suburb: 'Waterfall',
        languages: ['English', 'Afrikaans', 'Arabic'],
        avgResponseHours: 2.2,
        avgTransferDays: 67,
        priceBand: 2,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'commercial', 'bond-registration', 'investment-property'],
        bio: 'Corridor specialists for Midrand and Waterfall buyers needing fast bond registration alignment with originators.',
        firmHistory: 'Established 2016 to serve Gauteng’s northern growth corridor.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — UNISA'],
        memberships: ['Legal Practice Council'],
        awards: [],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Waterfall',
                address: 'Maxwell Office Park',
                suburb: 'Waterfall',
                city: 'Midrand',
                province: 'gauteng',
                coords: { lat: -25.9992, lng: 28.126 },
            },
        ],
        services: [...commonServices, 'commercial', 'investment-property'],
        performance: {
            avgTransferDays: 67,
            avgResponseHours: 2.2,
            clientSatisfactionPct: 92,
            repeatClientPct: 31,
            transfersCompleted: 610,
            successRatePct: 97.9,
            currentWorkload: 20,
            monthlyCases: 19,
            avgReview: 4.55,
            yearsActive: 10,
            responseRatePct: 93,
        },
        reviews: [
            review('r8', 'Kyle R.', 'buyer', 4.6, 'Bond registration speed', 'Guarantees issued faster than expected.', '2026-05-30', 8),
        ],
        documents: [{ label: 'Practice Certificate', type: 'PDF' }],
        phone: '+27 10 555 0177',
        email: 'matters@midrandmetro.demo',
        website: 'https://example.com/midrand',
        lastActiveAt: '2026-07-29T08:30:00Z',
        coords: { lat: -25.9992, lng: 28.126 },
    },
    {
        id: 'cc-08',
        slug: 'bloemfontein-title-works',
        firmName: 'Bloemfontein Title Works',
        attorneyName: 'Carla van Wyk',
        title: 'Conveyancer',
        verified: true,
        featured: false,
        logoInitials: 'BT',
        photoInitials: 'CV',
        accent: '#854D0E',
        rating: 4.4,
        reviewCount: 52,
        completedTransfers: 390,
        yearsInPractice: 7,
        province: 'free-state',
        city: 'Bloemfontein',
        suburb: 'Westdene',
        languages: ['Afrikaans', 'English'],
        avgResponseHours: 3.5,
        avgTransferDays: 78,
        priceBand: 1,
        acceptingNewClients: true,
        openToday: false,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'estate-transfers', 'bond-cancellation'],
        bio: 'Free State residential conveyancing with a reputation for plain-language updates and fair fees.',
        firmHistory: 'Independent Westdene practice since 2019.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — University of the Free State'],
        memberships: ['Legal Practice Council'],
        awards: [],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Westdene',
                address: '10 Second Avenue',
                suburb: 'Westdene',
                city: 'Bloemfontein',
                province: 'free-state',
                coords: { lat: -29.116, lng: 26.2 },
            },
        ],
        services: [...commonServices, 'estate-transfers'],
        performance: {
            avgTransferDays: 78,
            avgResponseHours: 3.5,
            clientSatisfactionPct: 90,
            repeatClientPct: 24,
            transfersCompleted: 390,
            successRatePct: 97.1,
            currentWorkload: 10,
            monthlyCases: 11,
            avgReview: 4.4,
            yearsActive: 7,
            responseRatePct: 88,
        },
        reviews: [
            review('r9', 'Hennie B.', 'seller', 4.4, 'Reliable Free State service', 'Kept our agent looped in throughout.', '2025-12-03', 4),
        ],
        documents: [{ label: 'Practice Certificate', type: 'PDF' }],
        phone: '+27 51 555 0133',
        email: 'hello@titleworks.demo',
        website: 'https://example.com/titleworks',
        lastActiveAt: '2026-07-26T12:00:00Z',
        coords: { lat: -29.116, lng: 26.2 },
    },
    {
        id: 'cc-09',
        slug: 'polokwane-property-law',
        firmName: 'Polokwane Property Law',
        attorneyName: 'Kgomotso Mabasa',
        title: 'Senior Associate',
        verified: true,
        featured: false,
        logoInitials: 'PP',
        photoInitials: 'KM',
        accent: '#166534',
        rating: 4.35,
        reviewCount: 41,
        completedTransfers: 280,
        yearsInPractice: 6,
        province: 'limpopo',
        city: 'Polokwane',
        suburb: 'Sterpark',
        languages: ['English', 'Northern Sotho', 'Tsonga'],
        avgResponseHours: 4.0,
        avgTransferDays: 80,
        priceBand: 1,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'family-transfers', 'bond-registration'],
        bio: 'Limpopo conveyancing with multilingual support for first-time buyers and family transfers.',
        firmHistory: 'Opened 2020 to expand professional conveyancing access in Polokwane.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — University of Limpopo'],
        memberships: ['Legal Practice Council'],
        awards: [],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Sterpark',
                address: '23 Biccard Street',
                suburb: 'Sterpark',
                city: 'Polokwane',
                province: 'limpopo',
                coords: { lat: -23.9045, lng: 29.4689 },
            },
        ],
        services: [...commonServices],
        performance: {
            avgTransferDays: 80,
            avgResponseHours: 4,
            clientSatisfactionPct: 89,
            repeatClientPct: 22,
            transfersCompleted: 280,
            successRatePct: 96.8,
            currentWorkload: 9,
            monthlyCases: 9,
            avgReview: 4.35,
            yearsActive: 6,
            responseRatePct: 87,
        },
        reviews: [
            review('r10', 'Thabo M.', 'buyer', 4.3, 'Patient guidance', 'First home — explained FICA calmly.', '2026-03-19', 3),
        ],
        documents: [{ label: 'Practice Certificate', type: 'PDF' }],
        phone: '+27 15 555 0144',
        email: 'desk@polokwanepl.demo',
        website: 'https://example.com/polokwane',
        lastActiveAt: '2026-07-25T09:00:00Z',
        coords: { lat: -23.9045, lng: 29.4689 },
    },
    {
        id: 'cc-10',
        slug: 'nelspruit-deed-partners',
        firmName: 'Nelspruit Deed Partners',
        attorneyName: 'Riaan Coetzee',
        title: 'Partner',
        verified: true,
        featured: false,
        logoInitials: 'ND',
        photoInitials: 'RC',
        accent: '#9A3412',
        rating: 4.45,
        reviewCount: 57,
        completedTransfers: 350,
        yearsInPractice: 9,
        province: 'mpumalanga',
        city: 'Mbombela',
        suburb: 'Sonheuwel',
        languages: ['Afrikaans', 'English', 'Swati'],
        avgResponseHours: 3.2,
        avgTransferDays: 76,
        priceBand: 2,
        acceptingNewClients: false,
        openToday: true,
        onlineConsultation: false,
        availability: 'busy',
        specialisations: ['residential', 'commercial', 'developments'],
        bio: 'Lowveld commercial and residential transfers with deep local deeds office experience.',
        firmHistory: 'Regional partnership practice serving Mbombela since 2015.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — University of Pretoria'],
        memberships: ['Legal Practice Council'],
        awards: [],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Sonheuwel',
                address: '7 Ferreira Street',
                suburb: 'Sonheuwel',
                city: 'Mbombela',
                province: 'mpumalanga',
                coords: { lat: -25.4753, lng: 30.9694 },
            },
        ],
        services: [...commonServices, 'commercial', 'developments'],
        performance: {
            avgTransferDays: 76,
            avgResponseHours: 3.2,
            clientSatisfactionPct: 91,
            repeatClientPct: 28,
            transfersCompleted: 350,
            successRatePct: 97.4,
            currentWorkload: 26,
            monthlyCases: 13,
            avgReview: 4.45,
            yearsActive: 9,
            responseRatePct: 89,
        },
        reviews: [
            review('r11', 'Sandra W.', 'investor', 4.5, 'Commercial leasehold transfer', 'Handled a complex commercial instruction.', '2026-04-02', 6),
        ],
        documents: [{ label: 'Practice Certificate', type: 'PDF' }],
        phone: '+27 13 555 0190',
        email: 'partners@nelspruitdeed.demo',
        website: 'https://example.com/nelspruit',
        lastActiveAt: '2026-07-24T15:45:00Z',
        coords: { lat: -25.4753, lng: 30.9694 },
    },
    {
        id: 'cc-11',
        slug: 'roodepoort-swift-title',
        firmName: 'Roodepoort Swift Title',
        attorneyName: 'Nomsa Khumalo',
        title: 'Conveyancer',
        verified: true,
        featured: true,
        logoInitials: 'RS',
        photoInitials: 'NK',
        accent: '#DC2626',
        rating: 4.75,
        reviewCount: 134,
        completedTransfers: 920,
        yearsInPractice: 11,
        province: 'gauteng',
        city: 'Roodepoort',
        suburb: 'Clearwater',
        languages: ['English', 'Zulu', 'Sotho'],
        avgResponseHours: 1.0,
        avgTransferDays: 58,
        priceBand: 2,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'bond-registration', 'bond-cancellation', 'sectional-title'],
        bio: 'West Rand speed specialists — consistently among the fastest average transfer durations on PropReady.',
        firmHistory: 'Founded 2015 with a process-engineered approach to residential conveyancing.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — University of Johannesburg'],
        memberships: ['Legal Practice Council'],
        awards: ['Fastest Transfer Partner 2025'],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Clearwater',
                address: 'Christiaan de Wet Rd',
                suburb: 'Clearwater',
                city: 'Roodepoort',
                province: 'gauteng',
                coords: { lat: -26.137, lng: 27.872 },
            },
        ],
        services: [...commonServices],
        performance: {
            avgTransferDays: 58,
            avgResponseHours: 1,
            clientSatisfactionPct: 95,
            repeatClientPct: 40,
            transfersCompleted: 920,
            successRatePct: 98.7,
            currentWorkload: 24,
            monthlyCases: 33,
            avgReview: 4.75,
            yearsActive: 11,
            responseRatePct: 99,
        },
        reviews: [
            review('r12', 'Jason T.', 'buyer', 4.8, 'Fastest transfer we have done', 'Registration in under two months.', '2026-06-20', 21, 'Speed with accuracy is our promise.'),
        ],
        documents: [
            { label: 'Practice Certificate', type: 'PDF' },
            { label: 'Office floorplan', type: 'Image' },
        ],
        phone: '+27 11 555 0220',
        email: 'swift@roodepoorttitle.demo',
        website: 'https://example.com/swift',
        lastActiveAt: '2026-07-30T11:50:00Z',
        coords: { lat: -26.137, lng: 27.872 },
    },
    {
        id: 'cc-12',
        slug: 'century-city-commercial-title',
        firmName: 'Century City Commercial Title',
        attorneyName: 'Daniel Abrahams',
        title: 'Commercial Conveyancer',
        verified: true,
        featured: false,
        logoInitials: 'CC',
        photoInitials: 'DA',
        accent: '#1E3A8A',
        rating: 4.65,
        reviewCount: 73,
        completedTransfers: 540,
        yearsInPractice: 13,
        province: 'western-cape',
        city: 'Cape Town',
        suburb: 'Century City',
        languages: ['English', 'Afrikaans'],
        avgResponseHours: 2.8,
        avgTransferDays: 72,
        priceBand: 4,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'limited',
        specialisations: ['commercial', 'developments', 'portfolio', 'investment-property'],
        bio: 'Premium commercial and development conveyancing for Century City and greater Cape Town corporates.',
        firmHistory: 'Commercial desk spun out of a national firm in 2013.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — UCT', 'LLM Commercial Law — UCT'],
        memberships: ['Legal Practice Council'],
        awards: ['Commercial Property Law Recognition 2023'],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Century City',
                address: 'Ratanga Road',
                suburb: 'Century City',
                city: 'Cape Town',
                province: 'western-cape',
                coords: { lat: -33.892, lng: 18.512 },
            },
        ],
        services: ['commercial', 'developments', 'portfolio', 'investment-property', 'sectional-title'],
        performance: {
            avgTransferDays: 72,
            avgResponseHours: 2.8,
            clientSatisfactionPct: 94,
            repeatClientPct: 45,
            transfersCompleted: 540,
            successRatePct: 98.4,
            currentWorkload: 15,
            monthlyCases: 12,
            avgReview: 4.65,
            yearsActive: 13,
            responseRatePct: 95,
        },
        reviews: [
            review('r13', 'InvestCo Ops', 'developer', 4.7, 'Complex sectional scheme', 'Board-ready reporting throughout.', '2026-02-28', 10),
        ],
        documents: [
            { label: 'Practice Certificate', type: 'PDF' },
            { label: 'Commercial capability deck', type: 'PDF' },
        ],
        phone: '+27 21 555 0400',
        email: 'commercial@cctitle.demo',
        website: 'https://example.com/cctitle',
        lastActiveAt: '2026-07-29T17:10:00Z',
        coords: { lat: -33.892, lng: 18.512 },
    },
    {
        id: 'cc-13',
        slug: 'ballito-shoreline-conveyancers',
        firmName: 'Ballito Shoreline Conveyancers',
        attorneyName: 'Megan Pillay',
        title: 'Principal Conveyancer',
        verified: true,
        featured: false,
        logoInitials: 'BS',
        photoInitials: 'MP',
        accent: '#0E7490',
        rating: 4.7,
        reviewCount: 99,
        completedTransfers: 510,
        yearsInPractice: 10,
        province: 'kwazulu-natal',
        city: 'Ballito',
        suburb: 'Ballito',
        languages: ['English', 'Zulu'],
        avgResponseHours: 1.6,
        avgTransferDays: 65,
        priceBand: 3,
        acceptingNewClients: true,
        openToday: true,
        onlineConsultation: true,
        availability: 'available',
        specialisations: ['residential', 'investment-property', 'sectional-title', 'developments'],
        bio: 'North Coast lifestyle and investment property transfers with virtual consultations for out-of-province buyers.',
        firmHistory: 'Ballito boutique practice opened in 2016.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer'],
        education: ['LLB — UKZN'],
        memberships: ['Legal Practice Council'],
        awards: [],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Ballito Lifestyle Centre',
                address: 'Compensation Beach Rd',
                suburb: 'Ballito',
                city: 'Ballito',
                province: 'kwazulu-natal',
                coords: { lat: -29.539, lng: 31.214 },
            },
        ],
        services: [...commonServices, 'investment-property', 'developments'],
        performance: {
            avgTransferDays: 65,
            avgResponseHours: 1.6,
            clientSatisfactionPct: 95,
            repeatClientPct: 34,
            transfersCompleted: 510,
            successRatePct: 98.5,
            currentWorkload: 17,
            monthlyCases: 16,
            avgReview: 4.7,
            yearsActive: 10,
            responseRatePct: 96,
        },
        reviews: [
            review('r14', 'Chloe A.', 'investor', 4.7, 'Holiday flat purchase', 'Virtual consult made it easy from Joburg.', '2026-05-05', 12),
        ],
        documents: [{ label: 'Practice Certificate', type: 'PDF' }],
        phone: '+27 32 555 0188',
        email: 'shore@ballitoc.demo',
        website: 'https://example.com/ballito',
        lastActiveAt: '2026-07-30T06:20:00Z',
        coords: { lat: -29.539, lng: 31.214 },
    },
    {
        id: 'cc-14',
        slug: 'sandton-legacy-notaries',
        firmName: 'Sandton Legacy Notaries',
        attorneyName: 'Adrian Molefe',
        title: 'Notary & Conveyancer',
        verified: true,
        featured: false,
        logoInitials: 'SL',
        photoInitials: 'AM',
        accent: '#4C1D95',
        rating: 4.8,
        reviewCount: 110,
        completedTransfers: 690,
        yearsInPractice: 18,
        province: 'gauteng',
        city: 'Johannesburg',
        suburb: 'Sandton',
        languages: ['English', 'French', 'Zulu'],
        avgResponseHours: 2.1,
        avgTransferDays: 69,
        priceBand: 4,
        acceptingNewClients: true,
        openToday: false,
        onlineConsultation: true,
        availability: 'limited',
        specialisations: ['trust-transfers', 'estate-transfers', 'portfolio', 'commercial'],
        bio: 'High-net-worth estate, trust and portfolio conveyancing with notarial depth for complex family structures.',
        firmHistory: 'Legacy Sandton notarial desk established in 2008.',
        qualifications: ['Admitted Attorney (RSA)', 'Conveyancer', 'Notary Public'],
        education: ['LLB — Wits', 'Diploma in Notarial Practice'],
        memberships: ['Legal Practice Council'],
        awards: ['Private Client Conveyancing Merit'],
        licences: ['LPC Fidelity Fund Certificate 2026'],
        offices: [
            {
                label: 'Maude Street',
                address: '5th Floor, Maude St',
                suburb: 'Sandton',
                city: 'Johannesburg',
                province: 'gauteng',
                coords: { lat: -26.105, lng: 28.054 },
            },
        ],
        services: ['trust-transfers', 'estate-transfers', 'portfolio', 'commercial', 'family-transfers', 'deceased-estates'],
        performance: {
            avgTransferDays: 69,
            avgResponseHours: 2.1,
            clientSatisfactionPct: 96,
            repeatClientPct: 52,
            transfersCompleted: 690,
            successRatePct: 99.0,
            currentWorkload: 14,
            monthlyCases: 10,
            avgReview: 4.8,
            yearsActive: 18,
            responseRatePct: 94,
        },
        reviews: [
            review('r15', 'Family Office SA', 'investor', 4.9, 'Trust transfer expertise', 'Navigated multi-entity structure cleanly.', '2026-01-08', 16),
        ],
        documents: [
            { label: 'Practice Certificate', type: 'PDF' },
            { label: 'Notary Certificate', type: 'PDF' },
        ],
        phone: '+27 11 555 0303',
        email: 'legacy@sandtonnotaries.demo',
        website: 'https://example.com/legacy',
        lastActiveAt: '2026-07-28T18:00:00Z',
        coords: { lat: -26.105, lng: 28.054 },
    },
];

export function getConveyancerBySlug(slug: string): ConveyancerProfile | undefined {
    return CONVEYANCERS.find((c) => c.slug === slug);
}

export function getConveyancerById(id: string): ConveyancerProfile | undefined {
    return CONVEYANCERS.find((c) => c.id === id);
}

export function getFeaturedConveyancers(): ConveyancerProfile[] {
    return CONVEYANCERS.filter((c) => c.featured);
}

export function listProvinces(): ProvinceSlug[] {
    return Array.from(new Set(CONVEYANCERS.map((c) => c.province)));
}

export function listCities(province?: ProvinceSlug | ''): string[] {
    const rows = province ? CONVEYANCERS.filter((c) => c.province === province) : CONVEYANCERS;
    return Array.from(new Set(rows.map((c) => c.city))).sort();
}

export function listSuburbs(province?: ProvinceSlug | '', city?: string): string[] {
    let rows = CONVEYANCERS;
    if (province) rows = rows.filter((c) => c.province === province);
    if (city) rows = rows.filter((c) => c.city.toLowerCase() === city.toLowerCase());
    return Array.from(new Set(rows.map((c) => c.suburb))).sort();
}

export function cityToSlug(city: string): string {
    return city
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-|-$/g, '');
}

export function findCityBySlug(province: ProvinceSlug, citySlug: string): string | undefined {
    return listCities(province).find((c) => cityToSlug(c) === citySlug);
}

export const PLATFORM_STATS = {
    verifiedConveyancers: CONVEYANCERS.filter((c) => c.verified).length,
    completedTransfers: CONVEYANCERS.reduce((s, c) => s + c.completedTransfers, 0),
    averageClientRating:
        Math.round(
            (CONVEYANCERS.reduce((s, c) => s + c.rating, 0) / CONVEYANCERS.length) * 10
        ) / 10,
    averageTransferTime: Math.round(
        CONVEYANCERS.reduce((s, c) => s + c.avgTransferDays, 0) / CONVEYANCERS.length
    ),
    citiesCovered: new Set(CONVEYANCERS.map((c) => c.city)).size,
    averageResponseHours:
        Math.round(
            (CONVEYANCERS.reduce((s, c) => s + c.avgResponseHours, 0) / CONVEYANCERS.length) * 10
        ) / 10,
    repeatClientPct: Math.round(
        CONVEYANCERS.reduce((s, c) => s + c.performance.repeatClientPct, 0) / CONVEYANCERS.length
    ),
    clientSatisfactionPct: Math.round(
        CONVEYANCERS.reduce((s, c) => s + c.performance.clientSatisfactionPct, 0) /
            CONVEYANCERS.length
    ),
};
