export const LEARN_MODULE_HIGHLIGHTS: Record<string, string[]> = {
    'winning-formula': ['Leads × Speed × Trust × Listings', 'Weekly scorecard method'],
    'how-to-get-leads': ['Farm area dominance', '5-minute response window'],
    'leads-to-clients': ['5-stage pipeline', 'First-call script structure'],
    'follow-up-system': ['7 touches in 14 days', 'Value on every contact'],
    'lead-conversion': ['Contact within 2 hours', 'Use pre-qualification data'],
    'buyer-psychology': ['Emotion vs logic', 'Ethical FOMO use'],
    'negotiation-skills': ['Win-win framing', 'Counter-offer tactics'],
    'winning-pitch': ['LAER objection framework', 'Buyer & seller scripts'],
    'understanding-homeloans': ['Pre-approval vs grant', 'Full cost breakdown'],
    'bond-origination': ['Originator partnerships', 'EAAB referral disclosure'],
    'transfer-and-registration': ['Attorney role-players', 'Post-OTP checklist'],
    'eaab-compliance': ['FFC & registration', 'Trust money rules'],
    'eaab-code-of-conduct': ['Core client duties', 'CPA & POPIA alignment'],
    'eaab-mandates-and-commission': ['Mandate types explained', 'Written disclosure'],
    'eaab-fidelity-fund-cpd': ['FFC renewal cycle', 'Annual CPD points'],
    'eaab-trust-money': ['Trust account golden rules', 'FICA at deposit'],
    'legal-basics': ['OTP essentials', 'FICA & POPIA duties'],
    'listing-tips': ['Photo-first marketing', 'Pricing with comparables'],
    'digital-marketing': ['PropReady + portals', 'Consistent brand presence'],
    'social-media-for-agents': ['Two-platform focus', 'Content that educates'],
    'email-and-nurture': ['POPIA-safe lists', '4-message buyer flow'],
    'listing-presentations': ['CMA preparation', 'Close for the mandate'],
    'working-with-sellers': ['Pricing conversations', 'Weekly seller updates'],
    'pricing-to-sell': ['Defensible CMA', 'Price review triggers'],
    'show-day-playbook': ['Same-day follow-up', 'Register every visitor'],
    'time-management': ['Lead-first mornings', 'Pipeline batching'],
    'agent-mistakes': ['Speed + personalisation', 'Compliance non-negotiables'],
    'crm-and-systems': ['5-stage pipeline', '15-min daily hygiene'],
    'daily-routine-top-producers': ['45-min lead block', 'Weekly planning anchors'],
};
