/** Central localStorage keys for PropReady session and data */
export const STORAGE_KEYS = {
    users: 'propReady_users',
    currentUser: 'propReady_currentUser',
    rememberUserEmail: 'propReady_rememberUserEmail',
    quizResult: 'propReady_quizResult',
    leads: 'propReady_leads',
    sellerInfo: 'propReady_sellerInfo',
    sellerProperties: 'propReady_sellerProperties',
    activeSellerPropertyId: 'propReady_activeSellerPropertyId',
    sellers: 'propReady_sellers',
    propertyQuizzes: 'propReady_propertyQuizzes',
    documentGrants: 'propReady_documentGrants',
    prequalSkipped: 'propReady_prequalSkipped',
    agents: 'propReady_agents',
    currentAgent: 'propReady_currentAgent',
    rememberAgentEmail: 'propReady_rememberAgentEmail',
    listedProperties: 'propReady_listedProperties',
    viewingAppointments: 'propReady_viewingAppointments',
    documents: 'propReady_documents',
    leadDocuments: 'propReady_leadDocuments',
    selectedOriginator: 'propReady_selectedOriginator',
    documentsSent: 'propReady_documentsSent',
    activity: 'propReady_activity',
    /** Latest full originator prequal snapshot (also stored per-user key) */
    fullPrequal: 'propReady_fullPrequal',
    selectedAgent: (userId: string) => `propReady_selectedAgent_${userId}`,
} as const;
